CREATE TABLE teams (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    name VARCHAR(100) NOT NULL,
    color CHAR(7) NOT NULL, -- např. #2196F3
    active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB;